# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build, Test and publish
env:
  BUILD_NUMBER: ${{ github.ref != 'refs/heads/main' && '' || github.run_number }}
  VERSION_NUMBER: ${{ vars.CURRENT_VERSION }}${{ github.ref == 'refs/heads/dev' && '-alpha.' || github.ref == 'refs/heads/release' && '-beta.' || '' }}
  PUBLISH: ${{ github.ref != 'refs/heads/dev' && github.ref != 'refs/heads/release' && github.ref != 'refs/heads/main' && 'no' || 'yes' }}

on:
  push:
    branches: [ "dev", "release", "main" ]  
  pull_request:
    branches: [ "dev", "release", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/Kuchulem.DotNet.EntityAttributeValue.Abstractions/
    - name: Build
      run: dotnet build -p:VersionPrefix=$VERSION_NUMBER$BUILD_NUMBER --no-restore ./src/Kuchulem.DotNet.EntityAttributeValue.Abstractions/
    - name: Test
      run: dotnet test --no-build --verbosity normal ./src/Kuchulem.DotNet.EntityAttributeValue.Abstractions/
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
      with:
        nuget-version: latest
        nuget-api-key: ${{ secrets.NUGET_KEY }}
      if: ${{ env.PUBLISH == 'yes' }}
    - name: Pack
      run: dotnet pack -p:VersionPrefix=$VERSION_NUMBER$BUILD_NUMBER ./src/Kuchulem.DotNet.EntityAttributeValue.Abstractions --no-build -o nuget/
      if: ${{ env.PUBLISH == 'yes' }}
    - name: Publish
      run: dotnet nuget push nuget/ -s https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }}
      if: ${{ env.PUBLISH == 'yes' }}
