# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test on Dev
env:
  LIB_VERSION: ${{ vars.CURRENT_VERSION }}-alpha.${{ github.run_number }}
on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/Kuchulem.DotNet.EntityAttributeValue.Abstractions/
    - name: Build
      run: dotnet build -p:VersionPrefix=$LIB_VERSION. --no-restore ./src/Kuchulem.DotNet.EntityAttributeValue.Abstractions/
    - name: Test
      run: dotnet test --no-build --verbosity normal ./src/Kuchulem.DotNet.EntityAttributeValue.Abstractions/
